name: 'Playwright Tests'

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests:
    needs:
      - ts-checks-linux
    uses: zondax/_workflows/.github/workflows/_checks-playwright.yaml@v6
    with:
      environment: dev